name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore CardapioApi/CardapioApi.sln

      - name: Build solution
        run: dotnet build CardapioApi/CardapioApi.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test CardapioApi/UnitTests/UnitTests.csproj --no-build --configuration Release
